### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by drewaight** [KIT-MBS/distruct#1]
Hi I have tried to install distruct in every way I know how (conda, pip, building from source with networkit) but I cant get test programs to run.

I have installed with biopython 1.77 because Bio.Alphabet is removed in 1.78

`Traceback (most recent call last):
  File "/SFS/user/ry/waight/anaconda3/envs/distruct/lib/python3.7/site-packages/distruct/__init__.py", line 30, in <module>
    from _diSTruct import Distructure
ImportError: /SFS/user/ry/waight/anaconda3/envs/distruct/lib/python3.7/site-packages/_diSTruct.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN9NetworKit6VectordVERKd
`

Do you have any advice on how to get distruct running? Thanks for your help!

**Comment by oskar-taubert** [comment]
Hi @drewaight, sorry the response took me a while.
I tested it again for Python >= 3.7 it should work with:


`
> python -m venv dsvenv
> source dsvenv/bin/activate
> pip install --upgrade pip
> git clone https://github.com/KIT-MBS/distruct.git
> cd distruct
> pip install cython
> pip install networkit==7.0
> pip install -e .
> pip install pytest
> python -m pytest distruct/tests/
`

Your error looks like it might have to do with the way anaconda does things.
I've set the biopython version for now, but I'll streamline the installation process and the dependency handling in the next update and fix the Bio.Alphabet deprecation issue.

If this doesn't help I would have to do testing with Anaconda.
